export const apiData = {
    movies: [
        {
            title: "Adão Negro",
            description: "O poderoso Adão Negro é libertado de sua tumba para lançar sua justiça cruel sobre a Terra.",
            imageSmall: "https://www.claquete.com.br/fotos/filmes/poster/13737_medio.jpg",
            imageBanner: "https://images6.alphacoders.com/128/1282231.jpg",
            linkVideo: "HluMG9tJXHM",
            category: "movies",
        },
        {
            title: "Jurassic Park",
            description: "Um parque de diversões com dinossauros geneticamente recriados se transforma em um pesadelo mortal quando os dinossauros escapam de suas gaiolas e começam a caçar os visitantes.",
            imageSmall: "https://cinepop.com.br/wp-content/uploads/2022/04/jurassic-world-poster-1.jpg",
            imageBanner: "https://images7.alphacoders.com/901/901700.jpg",
            linkVideo: "QWBKEmWWL38",
            category: "movies",
        },
        {
            title: "Piratas do Caribe: A Maldição do Pérola Negra",
            description: "O capitão Jack Sparrow forma uma improvável aliança com a filha de um governador para salvar sua amada pérola negra de uma tripulação amaldiçoada de piratas zumbis.",
            imageSmall: "https://br.web.img3.acsta.net/c_310_420/pictures/14/02/06/15/11/493568.jpg",
            imageBanner: "https://blogs.uai.com.br/opipoqueiro/wp-content/uploads/sites/54/2017/06/Piratas-do-Caribe-5-banner.jpeg",
            linkVideo: "Z0q5tkp4ZIw",
            category: "movies",
        },
        {
            title: "Matrix",
            description: "Um hacker descobre uma realidade virtual que é muito mais complicada e perigosa do que ele jamais imaginou.",
            imageSmall: "https://img.elo7.com.br/product/main/2679A20/big-poster-filme-matrix-lo03-tamanho-90x60-cm-geek.jpg",
            imageBanner: "https://images7.alphacoders.com/489/489657.png",
            linkVideo: "m8e-FF8MsqU",
            category: "movies",
        },
        {
            title: "Vingadores: Ultimato",
            description: "Os Vingadores embarcam em uma jornada final para tentar desfazer o dano causado por Thanos e restaurar a ordem no universo.",
            imageSmall: "https://www.themoviedb.org/t/p/w300_and_h450_bestv2/ulzhLuWrPK07P1YkdWQLZnQh1JL.jpg",
            imageBanner: "https://www.themoviedb.org/t/p/original/or06FN3Dka5tukK1e9sl16pB3iy.jpg",
            linkVideo: "TcMBFSGVi1c",
            category: "movies",
        },
        {
            title: "Star Wars: Uma Nova Esperança",
            description: "Luke Skywalker se junta a um grupo de rebeldes para combater o Império Galáctico e salvar a princesa Leia.",
            imageSmall: "https://play-lh.googleusercontent.com/urFmNCsqsU93qEKDmhrs60zl2rDki-XzdQpms01-P64kMX3VkGO0c7Sf2ira2mzbgwmM",
            imageBanner: "https://images3.alphacoders.com/111/1115520.jpg",
            linkVideo: "vZ734NWnAHA",
            category: "movies",
        },
        {
            title: "O Poderoso Chefão",
            description: "A história da família Corleone, chefiada pelo patriarca Vito Corleone, um dos mafiosos mais poderosos de Nova York.",
            imageSmall: "https://www.themoviedb.org/t/p/w300_and_h450_bestv2/3bhkrj58Vtu7enYsRolD1fZdja1.jpg",
            imageBanner: "https://images5.alphacoders.com/131/1315822.jpg",
            linkVideo: "S5DO2hSjBwY",
            category: "movies",
        },
        {
            title: "Titanic",
            description: "A história de amor épica entre Jack e Rose a bordo do navio mais famoso da história, o Titanic.",
            imageSmall: "https://lumiere-a.akamaihd.net/v1/images/titanic_teaser_poster_brazil_v2_987ab3f5.jpeg?region=0,0,770,1100",
            imageBanner: "https://images5.alphacoders.com/336/336486.jpg",
            linkVideo: "zCy5WQ9S4c0",
            category: "movies",
        },
        {
            title: "O Senhor dos Anéis: A Sociedade do Anel",
            description: "Um hobbit relutante, Frodo, começa uma jornada épica para destruir um anel maligno e impedir que Sauron conquiste o mundo.",
            imageSmall: "https://img.elo7.com.br/product/original/269274A/poster-o-senhor-dos-aneis-a-sociedade-do-anel-lo04-90x60-cm-presente-geek.jpg",
            imageBanner: "https://w.forfun.com/fetch/4f/4fc7f3e41526da3b0e6cec0afd032735.jpeg",
            linkVideo: "V75dMMIW2B4",
            category: "movies",
        },
        {
            title: "Eu, a Patroa e as Crianças",
            description: "As hilariantes situações de um homem que tenta equilibrar sua vida profissional com sua vida em família, que inclui sua esposa e três crianças travessas.",
            imageSmall: "https://i.pinimg.com/originals/76/32/f8/7632f8331d5394b8c4360a1673d5b8c0.jpg",
            imageBanner: "https://prod-ripcut-delivery.disney-plus.net/v1/variant/star/E9CACD423F012622896DB40F9145E3CCFE9C57DF292FAF88D6C3229A80AF1E0B/scale?width=1200&aspectRatio=1.78&format=jpeg",
            linkVideo: "88LaK9iF17w",
            category: "tvShows",
        },
        {
            title: "Dragon Ball",
            description: "As aventuras de Goku enquanto ele busca pelas esferas do dragão para obter desejos e proteger o mundo de ameaças poderosas.",
            imageSmall: "https://tm.ibxk.com.br/ms/images/highlights/000/053/748/2132.jpg",
            imageBanner: "https://images8.alphacoders.com/632/632011.jpg",
            linkVideo: "vzgOIMRySBE",
            category: "tvShows",
        },
        {
            title: "Os Simpsons",
            description: "As aventuras da família Simpson em Springfield, uma cidade cheia de personagens excêntricos.",
            imageSmall: "https://artworks.thetvdb.com/banners/posters/71663-15.jpg",
            imageBanner: "https://images7.alphacoders.com/128/1287382.jpg",
            linkVideo: "Lu1ovwGI9SI",
            category: "tvShows",
        },
        {
            title: "Chaves",
            description: "As comédias e travessuras de Chaves, Quico, Chiquinha e outros moradores de uma vila mexicana.",
            imageSmall: "https://a-static.mlcdn.com.br/450x450/dvd-chaves-em-desenho-animado-volume-1-top-disc/campinascomercio2/17516/824d3f546dabf2267394dbf00a7e1a1f.jpeg",
            imageBanner: "https://www.teahub.io/photos/full/334-3347990_banner-painel-festa-decorativo-chaves-1-5x1m-chaves.jpg",
            linkVideo: "RijB8wnJCN0",
            category: "tvShows",
        },
        {
            title: "Cavaleiros do Zodíaco",
            description: "As aventuras de jovens guerreiros chamados Cavaleiros do Zodíaco, que lutam para proteger a deusa Atena e o mundo contra ameaças míticas.",
            imageSmall: "https://ovicio.com.br/wp-content/uploads/2019/06/20190626-saintseiya_vertical_rgb_pt-br-724x1024.jpg",
            imageBanner: "https://wallpapercave.com/wp/wp3892355.jpg",
            linkVideo: "1TyKQbOu9EY",
            category: "tvShows",
        },
        {
            title: "Friends",
            description: "Um grupo de amigos vive diversas aventuras e desafios em Nova York enquanto enfrenta as alegrias e tristezas da vida.",
            imageSmall: "https://www.themoviedb.org/t/p/w300_and_h450_bestv2/f496cm9enuEsZkSPzCwnTESEK5s.jpg",
            imageBanner: "https://images3.alphacoders.com/112/1123157.jpg",
            linkVideo: "jAy6NJ_D5vU",
            category: "tvShows",
        },
        {
            title: "Breaking Bad",
            description: "Um professor de química do ensino médio se transforma em um poderoso chefão das drogas após ser diagnosticado com câncer terminal.",
            imageSmall: "https://ae01.alicdn.com/kf/HTB1AcvZcpLM8KJjSZFBq6xJHVXax/6-Escolhas-de-Arte-Breaking-Bad-Filme-Propaganda-Cartaz-Retro-Vintage-Kraft-Cartaz-Da-Lona-Adesivo.jpg",
            imageBanner: "https://images4.alphacoders.com/131/1315826.jpg",
            linkVideo: "HhesaQXLuRY",
            category: "series",
        },
        {
            title: "Game of Thrones",
            description: "Nobres lutam pelo controle do Trono de Ferro enquanto um antigo inimigo retorna após séculos de sono.",
            imageSmall: "https://s2.glbimg.com/ARgbPuSchwJ0112xhFjAT2-5Kf0=/e.glbimg.com/og/ed/f/original/2019/02/28/got-varys.jpg",
            imageBanner: "https://images.alphacoders.com/129/1294181.jpg",
            linkVideo: "rlR4PJn8b8I",
            category: "series",
        },
        {
            title: "Stranger Things",
            description: "Em uma pequena cidade, um grupo de crianças enfrenta forças sobrenaturais e segredos governamentais após o desaparecimento de um amigo.",
            imageSmall: "https://www.themoviedb.org/t/p/w300_and_h450_bestv2/x2LSRK2Cm7MZhjluni1msVJ3wDF.jpg",
            imageBanner: "https://images3.alphacoders.com/130/1306841.jpg",
            linkVideo: "XWxyRG_tckY",
            category: "series",
        },
        {
            title: "Friends",
            description: "Um grupo de amigos vive diversas aventuras e desafios em Nova York enquanto enfrenta as alegrias e tristezas da vida.",
            imageSmall: "https://www.themoviedb.org/t/p/w300_and_h450_bestv2/f496cm9enuEsZkSPzCwnTESEK5s.jpg",
            imageBanner: "https://images3.alphacoders.com/112/1123157.jpg",
            linkVideo: "jAy6NJ_D5vU",
            category: "series",
        },
        {
            title: "The Crown",
            description: "A história da rainha Elizabeth II e os eventos que moldaram a segunda metade do século XX.",
            imageSmall: "https://upload.wikimedia.org/wikipedia/pt/9/90/The-Crown-Poster-T1.jpg",
            imageBanner: "https://i.pinimg.com/originals/b8/ab/bb/b8abbb3a028a3062a48a0b55d120c3e4.jpg",
            linkVideo: "efuCCD8yF1E",
            category: "series",
        },
        {
            title: "Black Mirror",
            description: "Uma série de antologia que explora um futuro distópico e a influência da tecnologia na sociedade.",
            imageSmall: "https://cinema10.com.br/upload/series/series_212_pblsck.jpg",
            imageBanner: "https://wallpapers.com/images/featured/black-mirror-gbqux8n5pndwjdrn.jpg",
            linkVideo: "SGwHpzgqzPY",
            category: "series",
        },
        {
            title: "The Mandalorian",
            description: "Um caçador de recompensas viaja pelos confins da galáxia em busca de trabalho enquanto enfrenta perigos e desafios.",
            imageSmall: "https://www.jornalbomdia.com.br/tb_noticias/33647/Mandalorian%201.jpg",
            imageBanner: "https://images.alphacoders.com/131/1314093.jpeg",
            linkVideo: "XmI7WKrAtqs",
            category: "series",
        },
        {
            title: "Westworld",
            description: "Um parque de diversões futurista permite que os visitantes vivam suas fantasias mais selvagens, mas as coisas começam a dar errado.",
            imageSmall: "https://i.pinimg.com/originals/67/87/0f/67870f0fe5ea2ed8a3c87eef9e5adc01.jpg",
            imageBanner: "https://wallpapers.com/images/featured/westworld-qda7nwwwcqdpn8fb.jpg",
            linkVideo: "8h6t5eqg2GU",
            category: "series",
        },
        {
            title: "The Witcher",
            description: "Geralt de Rivia, um caçador de monstros mutante, luta para encontrar seu lugar em um mundo onde as pessoas são muitas vezes mais perversas do que as criaturas que ele caça.",
            imageSmall: "https://sobresagas.com.br/wp-content/uploads/2021/10/PT-BR_MM2_Main_Vertical_RGB_PRE.jpg",
            imageBanner: "https://images.alphacoders.com/131/1319720.jpeg",
            linkVideo: "cSqi-8kAMmM",
            category: "series",
        },
        
    ],
    categories: [
        { name: "Movies", type: "movies"},
        { name: "TV Shows", type: "tvShows"},
        { name: "Series", type: "series"},

    ]
};
